### ISSUE TITLE
Three-way ANOVA trouble

### ISSUE THREAD

**Issue by freddybrown1984** [0todd0000/spm1dmatlab#174]
Hello,
I'm assessing a 101-point time-series for force and/or velocity for two groups of participants who complete 10 sets of 10 jumps (I've averaged the data for each set rather than doing for every jump!) twice (separated by 14 days). I'm carrying out a three way ANOVA with 1 x between-group ariable (group) and 2 x repeated measures variables (set, bout). 

I've used the ex1d_anova3tworm.m package and have (I think!) worked out from the example data that the data should be arrange as in the screenshot (however, I'm a bit suspscious the between group variable isn't listed vertically). 
![data layout](https://user-images.githubusercontent.com/112722736/188214291-cb833801-099b-42f5-88dd-6c03c0534ee0.png)

This is then copied and pasted into Matlab. I run the following code after creating the following variables:
A = group (x2)
B = bout (x 2)
C = set (x 10)
Y = Data
SUBJ = subject
Data is arranged as a 101 series row for group 0, participant 0, bout 0, set0, before participant 1, 2, 3 etc, then the next set. 10 sets per bout, then repeated for bout 1, then the next group as in the attatched image (numbers continue horizontally to 101, with the vertical 1, 2, 3 representing participants):
![data layout2](https://user-images.githubusercontent.com/112722736/188213969-6827d0b3-55f9-470d-96b4-c81086b559ab.png)

However... when I try to run the ANOVA I get the followiung messages:

Error using spm1d.stats.anova.designs.ANOVA3rm/check_balanced (line 95)
Design must be balanced.
Error in spm1d.stats.anova.designs.ANOVA3rm (line 26)
            self.check_balanced()
Error in spm1d.stats.anova.designs.ANOVA3tworm (line 10)
            self@spm1d.stats.anova.designs.ANOVA3rm(A, B, C, SUBJ)
Error in spm1d.stats.anova3tworm (line 10)
design = spm1d.stats.anova.designs.ANOVA3tworm(A, B, C, SUBJ);
Error in Untitled (line 1)
spmlist   = spm1d.stats.anova3tworm(Y, A, B, C, SUBJ);

I have unequal groups (n = 8 and n = 9) and though that may have been the issue. However, even trying to run the data with one participant omitted to equalize the groups doesn't work. Furthermore, these unequal groups worked when I ran a 2 way (group x bout ANOVA with ex1d_anova2onerm.m with only the averages of each bout, rather than for each set

Can anyone help!? 
Thanks

**Comment by freddybrown1984** [comment]
This is regarding SPM,  btw

**Comment by 0todd0000** [comment]
Can you please send the sizes of the `A`, `B`, `C` and `SUBJ` arrays along with the unique values of each variable? Please just send the case where you have excluded one participant omitted to impose balance.

Please also explain what "group", "bout" and "set" represent.

**Comment by freddybrown1984** [comment]
Thanks so much for the speedy reponse - particularly seeing as it's a weekend. This is massively appreciated. 

Hopefully this spreadsheet will explain. On the first tab I've listed the variables as they're typed into Matlab (the top set includes the whole sample with unequal groups, the next one down has one participant deleted). The other three tabs are my "Y" variables, or variable of interest for ONLY the equalized groups (one deleted)
So in summary:
A  = 2 groups (160 rows in each). This is a between-measures variable (independant groups) using different recovery methods (compression stockings or placebo) between the two bouts of exercise
B = 4 lots of 80 rows (0 x 80, 1 x 80, 0 x 80, 1 x 80). These represent two sperate 2 bouts of exercise (repeated twice for each individual in 2 separate groups). I ask them to do 10 sets of 10 drop jumps (stepping off a platform, dropping to the floor from 0.6 m into a squat position, then jumping to fatigue their legs) as "Bout 0", then repeat after 2 weeks (Bout 1)
C = 0-9 represent 10 seperate "sets" of 10 drop-jumps (above), meaning that each row (repesenting the average force or velocity for a set of 10 jumps) is then repeated 10 times for "Bout 0", then another 10 times for "Bout 1". This is done for 8 participants in each group, leading to:10 sets (within) x 2 bouts (within) x 2 separate groups (between) of 8 individuals = 320 rows

[MatLabData - ExcludedNequalsONEforbalance.xlsx](https://github.com/0todd0000/spm1dmatlab/files/9484973/MatLabData.-.ExcludedNequalsONEforbalance.xlsx)

**Comment by 0todd0000** [comment]
From your description the design sounds balanced so I'm not sure what the problem is.

Can you please verify that the sizes of the input variables to `spm1d.stats.anova3tworm(Y, A, B, C, SUBJ)` are:
- `Y` : `360 x 101`
- `A`, `B`, `C`, `SUBJ` : all `360 x 1`

Unrelated to the balanced problem: from your description its sounds like this could be modeled using a two-way ANOVA, excluding "set". If each level of "set" is not directly comparable across participants, then I suggest calculating within-subject means for each of the four combinations of `A` and `B`, then using just these means in a two-way ANOVA. "Set" should be used only if there is direct experimental meaning to each level of set, like you are considering effects of fatigue across rapidly repeated sets. If they are simply repetitions then "set" could be excluded from the model.

**Comment by freddybrown1984** [comment]
Thanks again - yes, force or velocity over each set is likely to decline with fatigue, so I should reallly keep it in

Just to confirm, when I do the equal groups, Y = 320 x 101, and A, B, C, SUBJ = 320 x 1 (not 360? Screenshot attached... have I made an error here?). I then get:

_Index exceeds matrix dimensions.
Error in spm1d.stats.anova.factors.FactorNested/get_design_interaction_3way (line 105)
                            uuS = uS(kkk+1);
Error in spm1d.stats.anova.designs.ANOVA3tworm/assemble (line 38)
            XSBC   = self.S.get_design_interaction_3way(self.B, self.C);
Error in spm1d.stats.anova.designs.ANOVA3tworm (line 19)
            self      = assemble(self);
Error in spm1d.stats.anova3tworm (line 10)
design = spm1d.stats.anova.designs.ANOVA3tworm(A, B, C, SUBJ);
Error in freddythreeway (line 1)
spmlist   = spm1d.stats.anova3tworm(Y, A, B, C, SUBJ);_

If I try the groups of different n-number (n = 8, n = 9), it's then Y = 340 x 101, and A, B, C, SUBJ = 340 x 1 (8 subjects x 2 bouts x 10 sets = 160; 9 subjefcts x 2 bouts x 10 sets = 180; 180 + 160 = 340)

Thanks again!

 
  
![Picture1](https://user-images.githubusercontent.com/112722736/188699914-956cb4f7-703d-4c39-925d-a6db6a50bb8d.png)

**Comment by 0todd0000** [comment]
Yes, 320: 

`(2 groups) x (2 bouts) x (10 sets) x (8 subjects) = (320 observations)`

or more generally:

`40 x n observations`

where `n` is the number of subjects.

If the total number of observations is not `40 x n` then it will be imbalanced.

From the screenshot you sent it seems that all variables have 320 elements, so that does not explain the source of the imbalance.  To check in more detail, please copy-and-paste the output of the following commands into this thread:

```octave
X = [A; B; C; SUBJ]';
disp( X )
```

`X` should be a `(320, 4)` array of integers.

**Comment by freddybrown1984** [comment]
So it spat out a matrix as now saved in the attached file: 320 rows in each of 4 coloumns

[MatLabData - ExcludedNequalsONEforbalance.xlsx](https://github.com/0todd0000/spm1dmatlab/files/9506091/MatLabData.-.ExcludedNequalsONEforbalance.xlsx)

**Comment by freddybrown1984** [comment]
Hmmm... Still no luck. Tried editing the example data, loading another test then changing etc etc. 

One thing that DOES work is using the anova3**onerm**.m script - even on my datasets that explicitly number participants 0 - 15 (n = 16, total). This ONLY works on the equal groups (2 x n = 8; **not** on the n = 8, n = 9). Is there any way that a script for a 3way ANOVA with 2 rms may have been mistakenly saved under the wrong name (onerm)? The DoFs are given as:

Effects:
     A     F = [(1x101) array]    df = (1, 28)    h0reject = 0
     B     F = [(1x101) array]    df = (1, 28)    h0reject = 0
     C     F = [(1x101) array]    df = (9, 140)    h0reject = 1
    AB     F = [(1x101) array]    df = (1, 28)    h0reject = 0
    AC     F = [(1x101) array]    df = (9, 140)    h0reject = 1
    BC     F = [(1x101) array]    df = (9, 140)    h0reject = 1
   ABC     F = [(1x101) array]    df = (9, 140)    h0reject = 1

and I am trying to run an anova with 2 independent groups (A), both with n = 8 participants (SUBJ 0 - 7/ 8 - 15), doing 10 "set" of jumps (0 - 9), on two occasions (bout 0, bout 1). 

A = group (x2; 0, 1)
B = bout (x 2; 0, 1)
C = set (x 10; 0 - 9)
SUBJ = subject (0-15, made up of 0-7 x 0-9 sets x 0-1 bouts; 8-15 x 0-9 sets x 0-1 bouts)
Y = Data (0-7 x 0-9 sets x 0-1 bouts; 8-15 x 0-9 sets x 0-1 bouts - 320 rows)

My data should be set up with 2 rms (bout and set) BUT I can't see how the above script should work when I've explicitly named my partipants from 0 - 15, unless they're being treated as independent groups with B and C both rms.

**Comment by 0todd0000** [comment]
The data (`A`,`B`,`C`,`SUBJ`) does not generate an error for `spm1d.stats.anova3tworm` in the Python version of **spm1d**, so it is possible that this is a bug in the MATLAB version. Unfortunately I will not have access to MATLAB for about 10 days -- I am out of the office and the university's MATLAB license does not permit off-campus use. Can you wait about 10 days so I can check and fix the bug?

**Comment by freddybrown1984** [comment]
No worries at all - massive thanks for your help!

**Comment by freddybrown1984** [comment]
Hola!
Just a friendly reminder to see if there's anything that can be done with my 3-way ANOVA issue and.or to check to see if there's a bug with the MatLab script
Here's hoping you were away, chilling out, and had a nice time. Thanks

**Comment by 0todd0000** [comment]
Hello, apologies for the delay and thank you for the reminder!

I found the source of the problem:  a single index error on Line 105 of FactorNested.m;  the index should be `kkkk` and not `kkk`, so the code should look like this:

```octave
uuS = uS(kkkk+1);
```

I have pushed the changes to GitHub. Please try downloading the new version (version M.0.4.10, 2022.09.23) and re-running the script.

**Comment by freddybrown1984** [comment]
Amazing, thanks so much! I'll try it and get back to you... potentially even writing a song/poem in your honour. 

Thanks again - this will make all the difference to the work!

**Comment by freddybrown1984** [comment]
Hello, I'm still having problems, unfortunately

I've tried downloading the files both from "download .zip", as well as copying the code URL and going "source control --> retrieve" in the folder view of matlab from here: https://github.com/0todd0000/spm1dmatlab

I tried two ways. The first was to copy across all of the contents of the SPM8 folder, as well as the single example of ex1d_anova3tworm.m from the examples folder into my matlab folder/workspace. I then cut and pasted the code without the part that loads the original example, put in my own variables (A, B, C, SUBJ, Y) and run. This leads to the same old error: 

_(Error in spm1d.stats.anova.factors.FactorNested/get_design_interaction_3way (line 105)
                            uuS = uS(kkk+1);),_ 

making me think that this way must still be referring to old code. Copying and pasting the updated +SPM1d folder, or just the updated factornested file (+spm1 --> +stats --> + ANOVA --> + factors --> factornested.m) into the work space didnt work, either
                            
 So... then I tried simply running the anova3tworm.m script from the updated +stats folder I downloaded (NOT the original Ex1d_anova3tworm.m version) and am getting the message there are insufficient input arguments (despite having loaded A, B, C, SUBJ and Y).

![Picture2](https://user-images.githubusercontent.com/112722736/192144117-b678c624-cf6f-4435-a9d8-8402443fdd04.png)
_anova3tworm
Not enough input arguments.
Error in anova3tworm (line 10)
design = spm1d.stats.anova.designs.ANOVA3tworm(A, B, C, SUBJ)_;

I've tried inserting a Y, a "varargin" and both into the _design = spm1d.stats.anova.designs.ANOVA3tworm(A, B, C, SUBJ)_, but to no avail. I've double checked the downloaded factornested has kkkk (4 x ks) on line 105, and that appears okay

Sorry for further hassle. Your help is reatly appreciated

Thanks, 

Freddy

**Comment by 0todd0000** [comment]
A few points:

- If you are seeing `uS(kkk+1);)` on Line 105 of `spm1dmatlab/+spm1d/+stats/+anova/+factors/FactorNested.m`, then you have not correctly updated to the latest version. There should be a `kkkk` index as indicated [here](https://github.com/0todd0000/spm1dmatlab/blob/master/%2Bspm1d/%2Bstats/%2Banova/%2Bfactors/FactorNested.m).

- The `SPM8` contents are unmodified. The modification occurs elsewhere.

- While you are free to copy / replace individual components, this cannot be supported in this forum. Only original, intact and unmodified versions of the source code can be supported.

- If you are calling with the argument sequence `(A, B, C, SUBJ, Y)` then please try with `(Y, A, B, C, SUBJ)`.  The dependent variable `Y` is the first argument for all `spm1d.stats` procedures.

**Comment by freddybrown1984** [comment]
Thanks Todd. Can you please clarify the procedure for downloading and using the correct version? As stated in the message above, I downloaded a zip file from this link, which included the spm8 and +spm1d folders https://github.com/0todd0000/spm1dmatlab

I had previously used the original Ex1d_anova3tworm.m from “examples”, but then also used the anova3tworm.m script from the updated +stats folder. Am I on the right lines?

**Comment by 0todd0000** [comment]
To install the new version try the following:
1. Delete all current copies of spm1d
2. Remove all items containing "spm1d" from the MATLAB path
3. Download the new version
4. Set the MATLAB path to point to the new version

**Comment by freddybrown1984** [comment]
Thanks! So should I use the command Ex1d_anova3tworm.m  or anova3tworm.m!
?

**Comment by freddybrown1984** [comment]
Downloaded SPM1d and put in the MATLAB path (completely "clean"/new folder)
Created my variables - Y, A, B, C, SUBJ
Opened the SPM1 folder in the MATLAB window
Ran the anova3tworm.m script
Aparently not enouhj arguments?
![Picture12](https://user-images.githubusercontent.com/112722736/192384052-dd08c99e-9ab9-42f3-a8d5-c02b7c06acde.png)

Sorry for being a continual pain

**Comment by 0todd0000** [comment]
It is not possible to run functions from the Editor. Instead try entering the following command In the Command Window:

```octave
t = spm1d.stats.anova3tworm(Y, A, B, C, SUBJ);
```

**Comment by 0todd0000** [comment]
This warning can be ignored. Please see previous discussions of this topic here:
https://github.com/0todd0000/spm1d/issues?q=%22one+observation+found%22
Please feel free to continue the discussion in any of those threads if they do not answer your questions about this warning.

**Comment by 0todd0000** [comment]
I am closing this thread because the original issue (the bug in `spm1d.stats.anova3tworm`) appears to have been solved. Please feel free to re-open this issue if that bug persists.
