### ISSUE TITLE
Same p values for each condition in paired t-test

### ISSUE THREAD

**Issue by afetmustafaoglu** [0todd0000/spm1dmatlab#187]
Hello,
 I have been using SPM for my statistical analysis. However, we have run into a couple of problems with our results. My dataset consists of two groups: typically developing children and children with cerebral palsy. Each group has six subjects, and there is one gait cycle (mean of five trials) per subject. I directly modified the code you provided for MATLAB on GitHub and conducted a nonparametric paired t-test comparing Vicon and markerless in the CP and TD groups separately. The issue is that all the p values we got are the same for different conditions. I thought it would be related to iterations, though it seems not to be related to that. I have checked the documentation and could not find anything related to this. I am stuck at this point and wanted to ask you if you have any idea why this could happen. Is this because the sample size is so small that the code gives some sort of bug? 
Thank you for the help!

This is the code I used:
clc;
clear;
close all

yA = table2array(readtable('Vicon/knee_output/CP_mean_knee-Blaze.xlsx')); % Blazepose
yB = table2array(readtable('Vicon/knee_output/CP_mean_knee-Vicon.xlsx')); % Vicon

%(1) Conduct non-parametric test:
rng(0)
alpha      = 0.05;
two_tailed = true;
iterations = -1;
snpm       = spm1d.stats.nonparam.ttest_paired(yA, yB);
snpmi      = snpm.inference(alpha, 'two_tailed', two_tailed, 'iterations', iterations);
disp('Non-Parametric results')
disp( snpmi )
figure
snpmi.plot(); 
snpmi.plot_threshold_label(); snpmi.plot_p_values();
xlabel('Time (%)')
title('Knee (CP)')

**Comment by jzitnay** [comment]
Hi, If I understand what you're describing, I am seeing related behavior from the nonparametric paired t-test.  In this case, the inference spm is reporting conflicting results - e.g., h0reject = 1 , but p = 0.0625 with alpha = 0.0500.  Changing the alpha does not change the p-value (as one would expect); however, the decision on the null hypothesis and the spm plots are unaffected

snpm = spm1d.stats.nonparam.ttest_paired(spm_data{1}',spm_data{2}');

snpmi = snpm.inference(0.05,'two_tailed',true,'iterations',-1);
figure; snpmi.plot(); snpmi.plot_threshold_label(); snpmi.plot_p_values();
![image](https://github.com/0todd0000/spm1dmatlab/assets/16975709/aa9ee497-a12e-4457-b23d-e3ba23d89137)


snpmi = snpm.inference(0.01,'two_tailed',true,'iterations',-1);
figure; snpmi.plot(); snpmi.plot_threshold_label(); snpmi.plot_p_values();
![image](https://github.com/0todd0000/spm1dmatlab/assets/16975709/83b28b5a-9685-4fcd-9e71-066e3b8c3d95)

snpmi = snpm.inference(0.1,'two_tailed',true,'iterations',-1);
figure; snpmi.plot(); snpmi.plot_threshold_label(); snpmi.plot_p_values();
![image](https://github.com/0todd0000/spm1dmatlab/assets/16975709/87ba79e1-c9ac-4c42-8d89-06d7272c1945)

**Comment by 0todd0000** [comment]
Thank you for reporting these issues. To help me find the source of the problem, please tell me the size of the arrays `yA` and `spm_data{1}`

**Comment by afetmustafaoglu** [comment]
Hello,
The size of yA and yB are 6x101 for both.

**Comment by 0todd0000** [comment]
The problem may be related to small sample size. With just 6 observations there are a total of just 64 permutations, and thus just 64 values in the null distribution. With so few values it is difficult to achieve stable results in general.

Regardless, p-values greater than alpha are indeed concerning. They should be alpha or lower by definition, so there appears to be a miscalculation somewhere, likely secondary to the small sample size.

I'll need a bit of time to find and fix the problem, please stay tuned.

**Comment by jzitnay** [comment]
Where I was seeing this problem, spm_data{1} was 4x1033.  Using the dataset used by the examples, I could reproduce this behavior when yA and yB were 4x101, but 5 (or more) x101 behaved as one would expect.

**Comment by 0todd0000** [comment]
This case ( number of observations (N) = 4) is easier to address. With N=4 the maximum number of permutations is 16, so the minimum possible p-value is 1/16 = 0.0625.  This is why you are seeing the value 0.0625.

In general permutation methods work best when N is large, and they should generally be avoided when N is small. Regardless, the software should (a) not return a p-value larger than alpha, and/or (b) warn the user when N is small. I will check into possibilities and write again.

**Comment by 0todd0000** [comment]
Thank you for your patience.  I have fixed the underlying problems and have posted an updated version of the software to GitHub.  The current version is "M.0.4.11 (2023.10.24)"; the version you are using can be confirmed in the VERSION.txt file.

Below is a summary of the new behavior.

<br>
<br>
<br>

**Notation**:  The total number of possible permutations (`N`) is given by the sample size and design type, and this is directly related to the minimum possible p-value (p_min) as:

$p_{min} = \frac{1}{N}$

<br>
<br>
<br>


The new version of the software does the following:

<br>
<br>
<br>

**Case 1**:  (`alpha < p_min`)  - - >  error generated;   if the user-specified alpha-level is less than the minimum possible p-value an error similar to the following one is generated:

```
Error using spm1d.stats.nonparam.permuters.APermuter/check_iterations
alpha must be greater than 1/nPermTotal;  for this dataset nPermTotal=64 so minimum alpha is 0.01562; user-input alpha
= 0.010000
```

<br>
<br>
<br>

**Case 2**:  (`alpha >= p_min` with no clusters in results)  - - >  nothing done;   significance not reached, and results are identical to previous versions


<br>
<br>
<br>

**Case 3**:  (`alpha >= p_min` with clusters in results)  - - >  p-values capped at user-specified alpha;  cluster-level p-values have a maximum value of alpha by definition;  in previous versions cluster-level p-values could be larger than alpha for small sample sizes


<br>
<br>
<br>

@jzitnay  --- The behavior you saw previously (with cluster-level p=0.0625 when alpha=0.05) should be fixed;  you should now see cluster-level p-values with a maximum value of alpha.

@afetmustafaoglu  --- I believe that the new code will solve the problems you report as well, but I'm not certain. If the problem you report remains please report it here.

<br>
<br>

In general, it is best to avoid statistical inference of any kind for very small sample sizes. If you are unable to avoid conducting inference for these small sample sizes, note that permutation-based inference (the type of nonparametric inference that **spm1d** uses) is not really designed to work with very small sample sizes, and it works increasingly better the larger the sample size becomes.

Small sample sizes pose theoretical problems for all types of inference, both inside and outside **spm1d**. The problems you have reported are evidence of this. **spm1d** previously did not handle these problems well so I thank you very much for reporting these problems.

**Comment by afetmustafaoglu** [comment]
Hi Todd,

Thank you for your quick response and the new version. I just tried the test again with the new version. However, unfortunately, I still get the same p values as before.

**Comment by 0todd0000** [comment]
@afetmustafaoglu
> Thank you for your quick response and the new version. I just tried the test again with the new version. However, unfortunately, I still get the same p values as before.

Apologies, I may have misinterpreted your original post.  You asked above:

> "Is this because the sample size is so small that the code gives some sort of bug?"

Possibly, but it may actually not be a bug. It it possibly just a consequence of small-sample permutation testing, which can give relatively poor resolution probability densities. Regardless, I don't see anything odd in your code so we need to consider this further. You also wrote above:

> "...all the p values we got are the same for different conditions"

and

> "I thought it would be related to iterations, though it seems not to be related to that."

Can you please clarify:
- What are the actual p-values?
- What values of `iterations` did you try?
- What are the "different conditions"?

**Comment by afetmustafaoglu** [comment]
Hi, 

Certainly! I have two groups. One is healthy and one has cerebral palsy, and each group consists of six people. What I am testing is how this markerless method behaves in these two particular groups. I compare this markerless method to the gold standard in CP and healthy groups separately for knee, ankle, and hip angles. So in short, I am trying to see the differences between these methods for cerebral palsy and healthy participants. By different conditions, I meant, for instance, markerless vs. marker-based in CP for ankle angle, hip angle, and knee angle. Then same for TD.

The waveform and the clusters make sense for each condition. However, the p values were 0.016 for each result I got. I tried first with 64 and -1, then realized it was essentially the same thing. Then I tried with 20, 30, 40, and so on (mostly random numbers). The p values changed but were the same for each condition. So I have decided to use the default, which I guess is -1.

I hope this explains the situation well. Here is an example of the results I got. Thank you so much for your help.
![hip-CP](https://github.com/0todd0000/spm1dmatlab/assets/98603410/eaf3703e-8bda-42ff-93a5-6f3350b6d63a)

![ankle-CP](https://github.com/0todd0000/spm1dmatlab/assets/98603410/8a8fd507-f1fe-49cd-acb7-923f0a5130c5)

![ankle-TD](https://github.com/0todd0000/spm1dmatlab/assets/98603410/14176162-dd71-4e45-9ad8-3a92875e18eb)

**Comment by 0todd0000** [comment]
OK, thank you for clarifying. This is not a bug, it instead a limitation of both permutation techniques and small samples. When there are just six observations the total possible number of permutations is 64, which means that the minimum possible p-value is 1/64 = 0.0156. This is why you are repeatedly seeing p-values of 0.0156.

**Comment by afetmustafaoglu** [comment]
Thank you for the explanation. Is there a way to avoid this then for instance by changing the iterations for each condition? I would assume no but just to make sure wanted to ask.

**Comment by 0todd0000** [comment]
Changing the iterations for each condition is not a good idea. Generally permutation approaches should have at least 10,000 iterations, For small samples sizes --- like this case when there are just 64 permutations --- they are not very useful.  If the total number of permutations is less than 10,000 then the only reasonable approach is to use all permutations. So in this case: either (a) use `-1` for all or (b) increase the sample size.
